# Change these first
owner: NoCodeKR # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Bubble
    url: https://bubble.io/
  - name: Webflow
    url: https://webflow.com/
  - name: Webflow
    url: https://wappler.io/
  - name: FlutterFlow
    url: https://flutterflow.io/
  - name: V.One
    url: https://www.yourvone.com/
  - name: Glide
    url: https://www.glideapps.com/
  - name: Stacker
    url: https://www.stackerhq.com/
  - name: Softr
    url: https://www.softr.io/
  - name: Adalo
    url: https://www.adalo.com/
  - name: Pory
    url: https://pory.io/
  - name: Sheet2Site
    url: https://www.sheet2site.com/
  - name: Table2Site
    url: https://table2site.com/
  - name: Squarespace
    url: https://www.squarespace.com/
  - name: Carrd
    url: https://carrd.co/
  - name: Tilda
    url: https://tilda.cc/
  - name: Wix
    url: https://www.wix.com/
  - name: WordPress
    url: https://wordpress.com/
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** for No-Code"
  introMessage: 노코드 서비스를 모니터링 합니다.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
